---- OUTPUT (stdout) ----
Error: Error: Command failed: python3 /tmp/game#4#3dfbcd09-5aff-44f8-9544-4c411b6e6a44-xF2c4u/team#cava.pyz serve 9002
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/game#4#3dfbcd09-5aff-44f8-9544-4c411b6e6a44-xF2c4u/team#cava.pyz/__main__.py", line 2, in <module>
  File "/tmp/game#4#3dfbcd09-5aff-44f8-9544-4c411b6e6a44-xF2c4u/team#cava.pyz/main.py", line 24, in <module>
  File "/tmp/game#4#3dfbcd09-5aff-44f8-9544-4c411b6e6a44-xF2c4u/team#cava.pyz/strategy/strategy.py", line 4, in <module>
ModuleNotFoundError: No module named 'utils'

---- ERRORS (stderr) ----
Error: Command failed: python3 /tmp/game#4#3dfbcd09-5aff-44f8-9544-4c411b6e6a44-xF2c4u/team#cava.pyz serve 9002
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/game#4#3dfbcd09-5aff-44f8-9544-4c411b6e6a44-xF2c4u/team#cava.pyz/__main__.py", line 2, in <module>
  File "/tmp/game#4#3dfbcd09-5aff-44f8-9544-4c411b6e6a44-xF2c4u/team#cava.pyz/main.py", line 24, in <module>
  File "/tmp/game#4#3dfbcd09-5aff-44f8-9544-4c411b6e6a44-xF2c4u/team#cava.pyz/strategy/strategy.py", line 4, in <module>
ModuleNotFoundError: No module named 'utils'

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:517:28)
    at Pipe.<anonymous> (node:net:351:12) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'python3 /tmp/game#4#3dfbcd09-5aff-44f8-9544-4c411b6e6a44-xF2c4u/team#cava.pyz serve 9002',
  stdout: '',
  stderr: 'Traceback (most recent call last):\n' +
    '  File "<frozen runpy>", line 198, in _run_module_as_main\n' +
    '  File "<frozen runpy>", line 88, in _run_code\n' +
    '  File "/tmp/game#4#3dfbcd09-5aff-44f8-9544-4c411b6e6a44-xF2c4u/team#cava.pyz/__main__.py", line 2, in <module>\n' +
    '  File "/tmp/game#4#3dfbcd09-5aff-44f8-9544-4c411b6e6a44-xF2c4u/team#cava.pyz/main.py", line 24, in <module>\n' +
    '  File "/tmp/game#4#3dfbcd09-5aff-44f8-9544-4c411b6e6a44-xF2c4u/team#cava.pyz/strategy/strategy.py", line 4, in <module>\n' +
    "ModuleNotFoundError: No module named 'utils'\n"
}
